monty problem 구현
upstage-git-sample-team-10/team-fizzbuzz pull request #6
Opened 2023-11-17 10:38 UTC by Sungfeelgood

#3 에 대한 구현작업

resolve #3 

변경사항

- montyhall.py에 대한 업데이트

To reviewers

2023-11-17 10:39 UTC, HojunJ requested changes

2023-11-17 10:39 UTC, HojunJ commented on montyhall.py
> -print('montyhoel sample')
샘플코드는 삭제 부탁드립니다

2023-11-17 10:43 UTC, HojunJ approved these changes

2023-11-17 10:46 UTC, merged

2024-01-16 05:54 UTC, Sungfeelgood commented on montyhall.py
> -print('montyhoel sample')
네